window.team = [
  {
    name: "Кирил Фесюн",
    age: 23,
    number: 23,
    position: "Голкіпер",
    nationality: "Україна",
    photo: "https://shakhtar.com/-/media/fcsd/players/fesiun-kiril/fesiun_bio_25_26.png?h=610&iar=0&w=473",
  },
  {
    name: "Дмитро Різник",
    age: 26,
     number: 31,
     position: "Голкіпер",
     nationality: "Україна",
     photo: "https://shakhtar.com/-/media/fcsd/players/riznyk-dmytro/riznyk_bio_25_26.png?h=610&iar=0&w=473",
  },
   {
    name: "Денис Твардовський",
    age: 22,
     number: 48,
     position: "Голкіпер",
     nationality: "Україна",
     photo: "https://shakhtar.com/-/media/fcsd/players/tvardovskyi/tvardovskyi_bio_25_26.png?h=610&iar=0&w=473",
  },
  {
    name: "Дієго Арройо",
    age: "20",
    number: "3",
    position: "Захістник",
    nationality: "Болівія",
    photo: "https://shakhtar.com/-/media/fcsd/players/arroyo-diego/arroyo_bio_25_26.png?h=610&iar=0&w=473",
  },
  {
    name: "Марлон Сантос",
    age: "30",
    number: "4",
    position: "Захістник",
    nationality: "Бразілія",
    photo: "https://shakhtar.com/-/media/fcsd/players/marlon/marlon_santos_bio_25_26.png?h=610&iar=0&w=473",
  },
  {
    name: "Валерій Бондар",
    age: "26",
    number: "5",
    position: "Захістник",
    nationality: "Україна",
    photo: "https://shakhtar.com/-/media/fcsd/players/bondar-valeriy/bondar_bio_25_26.png?h=610&iar=0&w=473",
  },
  {
    name: "Педро Енріке",
    age: "23",
    number: "13",
    position: "Захістник",
    nationality: "Бразілія",
    photo: "https://shakhtar.com/-/media/fcsd/players/pedrinho_pedro-henrique-azevedo-pereira/pedro_henrique_bio_25_26.png?h=610&iar=0&w=473",
  },
  {
    name: "Іраклі Азаров",
    age: "23",
    number: "16",
    position: "Захістник",
    nationality: "Грузія",
    photo: "https://shakhtar.com/-/media/fcsd/players/azarov-irakli/azarov_bio_25_26.png?h=610&iar=0&w=473",
  },
  {
    name: "Вінісіус Тобіас",
    age: "21",
    number: "17",
    position: "Захістник",
    nationality: "Бразілія",
    photo: "https://shakhtar.com/-/media/fcsd/players/vinicius-tobias/tobias_bio_25_26.png?h=610&iar=0&w=473",
  },
  {
    name: "Алаа Грам",
    age: "24",
    number: "18",
    position: "Захістник",
    nationality: "Туніс",
    photo: "https://shakhtar.com/-/media/fcsd/players/ghram-alaa/ghram_bio_25_26.png?h=610&iar=0&w=473",
  },
  {
    name: "Микола Матвієнко",
    age: "29",
    number: "22",
    position: "Захістник",
    nationality: "Україна",
    photo: "https://shakhtar.com/-/media/fcsd/players/22-mykola-matviienko/matviienko_bio_25_26.png?h=610&iar=0&w=473",
  },
  {
    name: "Юхим Конопля",
    age: "26",
    number: "26",
    position: "Захістник",
    nationality: "україна",
    photo: "https://shakhtar.com/-/media/fcsd/players/konoplya/konoplia_bio_25_26.png?h=610&iar=0&w=473",
  },

  {
    name: "Мар'ян Фарина",
    age: "22",
    number: "74",
    position: "Захістник",
    nationality: "Україна",
    photo: "https://shakhtar.com/-/media/fcsd/players/faryna-marian/faryna_bio_25_26.png?h=610&iar=0&w=473",
  },
  {
    name: "Марлон Гомес",
    age: "21",
    number: "6",
    position: "Півзахістник",
    nationality: "Бразілія",
    photo: "https://shakhtar.com/-/media/fcsd/players/gomes-marlon/marlon_gomes_bio_25_26.png?h=610&iar=0&w=473",
  },
  {
    name: "Егіналду",
    age: "21",
    number: "7",
    position: "Півзахістник",
    nationality: "Бразілія",
    photo: "https://shakhtar.com/-/media/fcsd/players/eguinaldo/eguinaldo_bio_25_26.png?h=610&iar=0&w=473",
  },
  {
    name: "Дмитро Криськив",
    age: "24",
    number: "8",
    position: "Півзахістник",
    nationality: "Україна",
    photo: "https://shakhtar.com/-/media/fcsd/players/kryskiv-dmytro/kryskiv_bio_25_26.png?h=610&iar=0&w=473",
  },
  {
    name: "Мар'ян Швед",
    age: "28",
    number: "9",
    position: "Півзахістник",
    nationality: "Україна",
    photo: "https://shakhtar.com/-/media/fcsd/players/shved-marian/shved_bio_25_26.png?h=610&iar=0&w=473",
  },
  {
    name: "Педріньо",
    age: "27",
    number: "10",
    position: "Півзахістник",
    nationality: "Бразілія",
    photo: "https://shakhtar.com/-/media/fcsd/players/pedrinho/pedrinho_bio_25_26.png?h=610&iar=0&w=473",
  },
  {
    name: "Невертон",
    age: "20",
    number: "11",
    position: "Півзахістник",
    nationality: "Бразілія",
    photo: "https://shakhtar.com/-/media/fcsd/players/newerton/newertton_bio_25_26.png?h=610&iar=0&w=473",
  },
  {
    name: "Ізакі Сілва",
    age: "18",
    number: "14",
    position: "Півзахістник",
    nationality: "Бразілія",
    photo: "https://shakhtar.com/-/media/fcsd/players/isaque-silva/isaque_silva_bio_2025-09-18.png?h=610&iar=0&w=473",
  },
  {
    name: "Антон Глущенко",
    age: "21",
    number: "20",
    position: "Півзахістник",
    nationality: "Україна",
    photo: "https://shakhtar.com/-/media/fcsd/players/hlushchenko/hlushchenko_bio__25_26.png?h=610&iar=0&w=473",
  },
  {
    name: "Артем Бондаренко",
    age: "25",
    number: "21",
    position: "Півзахстник",
    nationality: "Україна",
    photo: "https://shakhtar.com/-/media/fcsd/players/bondarenko-artem/bondarenko_bio_25_26.png?h=610&iar=0&w=473",
  },
  {
    name: "Віктор Цуканов",
    age: "19",
    number: "24",
    position: "Півзахістник",
    nationality: "Україна",
    photo: "https://shakhtar.com/-/media/fcsd/players/under_19/tsukanov/tsukanov_bio_25_26.png?h=610&iar=0&w=473",
  },

  {
    name: "Олег Очеретько",
    age: "22",
    number: "27",
    position: "Півзахістник",
    nationality: "Україна",
    photo: "https://shakhtar.com/-/media/fcsd/players/ocheretko-oleh/ocheretko_bio_25_26.png?h=610&iar=0&w=473",
  },
  {
    name: "Єгор Назарина",
    age: "28",
    number: "27",
    position: "Півзахістник",
    nationality: "Україна",
    photo: "https://shakhtar.com/-/media/fcsd/players/nazaryna/nazaryna_bio_25_26.png?h=610&iar=0&w=473",
  },

  {
    name: "Аллісон Сантана",
    age: "20",
    number: "30",
    position: "Півзахістник",
    nationality: "Бразілія",
    photo: "https://shakhtar.com/-/media/fcsd/players/alisson/alisson_bio_25_26.png?h=610&iar=0&w=473",
  },
  {
    name: "Лукаc Феррейра",
    age: "19",
    number: "37",
    position: "Півзахістник",
    nationality: "Бразілія",
    photo: "https://shakhtar.com/-/media/fcsd/players/ferreira-lucas/lukasferreira_bio_25_26.png?h=610&iar=0&w=473",
  },
   {
    name: "Лассіна Траоре",
    age: "24",
    number: "2",
    position: "Нападник",
    nationality: "Буркін-Фасо",
    photo: "https://shakhtar.com/-/media/fcsd/players/traore-lassina/traore_bio_25_26.png?h=610&iar=0&w=473",
  },
   {
    name: "Кауан Еліас",
    age: "19",
    number: "19",
    position: "Нападник",
    nationality: "Бразілія",
    photo: "https://shakhtar.com/-/media/fcsd/players/elias-kaua/elias_bio_25_26.png?h=610&iar=0&w=473",
  },
   {
    name: "Лука Мейрелліш",
    age: "18",
    number: "49",
    position: "Нападник",
    nationality: "Бразілія",
    photo: "https://shakhtar.com/-/media/fcsd/players/luca-meirelles/luca_meirelles_bio_2025-09-18.png?h=610&iar=0&w=473",
  },
];
window.coaches = [
    {
    name: "Арда Туран",
    age: 38,
    position: "Тренерский штаб",
    coach: "Головний тренер",
    nationality: "Турція",
    photo: "https://shakhtar.com/-/media/fcsd/coaches/first_team/arda-turan/turan_p2.png?h=610&iar=0&w=473"
  },
  {
    name: "Керем Яваш",
    age: 41,
    position: "Тренерский штаб",
    coach: "Ассистент головного тренера",
    nationality: "Турція",
    photo: "https://shakhtar.com/-/media/fcsd/coaches/first_team/kerem-yavas/yava_p2.png?h=610&iar=0&w=473"
  },
   {
    name: "Сінан Сарікунт",
    age: 38,
    position: "Тренерский штаб",
    coach: "Ассистент головного тренера",
    nationality: "",
    photo: "https://shakhtar.com/-/media/fcsd/coaches/first_team/sinan-sarikurt/sarkurt_p2.png?h=610&iar=0&w=473"
  },
   {
    name: "Карло Ніколіні",
    age: 55,
    position: "Тренерский штаб",
    coach: "Ассистент головного тренера",
    nationality: "Італія",
    photo: "https://shakhtar.com/-/media/fcsd/coaches/first_team/carlo-nicolini/nicolini_p2.png?h=610&iar=0&w=473"
  },
   {
    name: "Окан Джан Янтир",
    age: 46,
    position: "Тренерский штаб",
    coach: "Особистий Консультант",
    nationality: "Турція",
    photo: "https://shakhtar.com/-/media/fcsd/coaches/first_team/okan-can-yantir/yantir_p2.png?h=610&iar=0&w=473"
  },
   {
    name: "Емрах Каракован",
    age: 41,
    position: "Тренерский штаб",
    coach: "Тренер воротарів",
    nationality: "Турція",
    photo: "https://shakhtar.com/-/media/fcsd/coaches/first_team/emrah-karakovan/karakovan_p2.png?h=610&iar=0&w=473"
  },
   {
    name: "Андрій Пятов",
    age: 41,
    position: "Тренерский штаб",
    coach: "Тренер воротарів",
    nationality: "Україна",
    photo: "https://shakhtar.com/-/media/fcsd/coaches/first_team/andrii-piatov/piatov_p2_.png?h=610&iar=0&w=473"
  },
   {
    name: "Утку Алемдароглу",
    age: 45,
    position: "Тренерский штаб",
    coach: "Тренер з фізподготовки",
    nationality: "Турція",
    photo: "https://shakhtar.com/-/media/fcsd/coaches/first_team/utku-alemdaroglu/alemdarolu_p2.png?h=610&iar=0&w=473"
  },
   {
    name: "Іван Баштовий",
    age: 38,
    position: "Тренерский штаб",
    coach: "Тренер з фізподготовки",
    nationality: "Україна",
    photo: "https://shakhtar.com/-/media/fcsd/coaches/first_team/ivan-bashtovyi/bashtovyi_bio_2025.png?h=610&iar=0&w=473"
  },
   {
    name: "Радіон Пальцун",
    age: 38,
    position: "Тренерский штаб",
    coach: "Аналітік",
    nationality: "Україна",
    photo: "https://shakhtar.com/-/media/fcsd/coaches/first_team/radion-paltsun/paltsun_bio_2025.png?h=610&iar=0&w=473"
  },
   {
    name: "Мерт Сомай",
    age: 39,
    position: "Тренерский штаб",
    coach: "Аналітік",
    nationality: "Турція",
    photo: "https://shakhtar.com/-/media/fcsd/coaches/first_team/mert-somay/somay_p2.png?h=610&iar=0&w=473"
  },
   {
    name: "Олексій Гай",
    age: 42,
    position: "Тренерский штаб",
    coach: "Аналітік",
    nationality: "Україна",
    photo: "https://shakhtar.com/-/media/fcsd/coaches/first_team/oleksii-hai/gai_p2.png?h=610&iar=0&w=473"
  },
];
  window.matches = [
{
  date: "5-10-25",
  opponent: "ЛНЗ Черкаси",
  time: "17:00",
  score: "",
  place: "Арена Львів, Львів",
  competition: "УПЛ",
},
{
  date: "18-10-25",
  opponent: "Полісся Житомир",
  time: "17:00",
  score: "",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
},
{
date: "23-10-25",
opponent: "Легія Варшава",
time: "18:45",
score: "",
place: "Хенріг Рейман, Краков",
competition: "Ліга Конференцй",
},
{
  date: "26-10-25",
  opponent: "Кудрівка",
  time: "14:30",
  score: "",
  place: "Арена Львів, Львів",
  competition: "УПЛ",
},
{
date: "28-10-25",
opponent: "Динамо Київ",
time: "16:00",
score: "",
place: "Стадіон імені Лобановського, Київ",
competition: "Кубок України",
},
{
  date: "6-11-25",
  opponent: "Бре́йдаблік",
  time: "18:45",
  score: "",
  place: "Хенрік-Рейман стадіон, Краків",
  competition: "Ліга Конференцій",
}
];
