window.team = [
  {
     name: "Кирил Фесюн",
     age: "23",
     number: "23",
     position: "Воротар",
     nationality: "Україна",
     photo: "https://shakhtar.com/-/media/fcsd/players/fesiun-kiril/fesiun_bio_25_26.png?h=610&iar=0&w=473",
     goals: "",
     assist: "",
     matches: "7",
  },
  {
     name: "Дмитро Різник",
     age: "26",
     number: "31",
     position: "Воротар",
     nationality: "Україна",
     photo: "https://shakhtar.com/-/media/fcsd/players/riznyk-dmytro/riznyk_bio_25_26.png?h=610&iar=0&w=473",
     goals: "",
     assist: "",
     matches: "25",
  },
  {
     name: "Денис Твардовський",
     age: "22",
     number: "48",
     position: "Воротар",
     nationality: "Україна",
     photo: "https://shakhtar.com/-/media/fcsd/players/tvardovskyi/tvardovskyi_bio_25_26.png?h=610&iar=0&w=473",
     goals: "",
     assist: "",
     matches: "",
  },
  {
     name: "Дієго Арройо",
     age: "20",
     number: "3",
     position: "Захистник",
     nationality: "Болівія",
     photo: "https://shakhtar.com/-/media/fcsd/players/arroyo-diego/arroyo_bio_25_26.png?h=610&iar=0&w=473",
     goals: "",
     assist: "",
     matches: "",
  },
  {
     name: "Марлон Сантос",
     age: "30",
     number: "4",
     position: "Захистник",
     nationality: "Бразілія",
     photo: "https://shakhtar.com/-/media/fcsd/players/marlon/marlon_santos_bio_25_26.png?h=610&iar=0&w=473",
     goals: "",
     assist: "2",
     matches: "8",
  },
  {
     name: "Валерій Бондар",
     age: "26",
     number: "5",
     position: "Захистник",
     nationality: "Україна",
     photo: "https://shakhtar.com/-/media/fcsd/players/bondar-valeriy/bondar_bio_25_26.png?h=610&iar=0&w=473",
     goals: "2",
     assist: "1",
     matches: "30",
  },
  {
     name: "Педро Енріке",
     age: "23",
     number: "13",
     position: "Захистник",
     nationality: "Бразілія",
     photo: "https://shakhtar.com/-/media/fcsd/players/pedrinho_pedro-henrique-azevedo-pereira/pedro_henrique_bio_25_26.png?h=610&iar=0&w=473",
     goals: "1",
     assist: "4",
     matches: "24",
  },
  {
     name: "Іраклі Азаров",
     age: "23",
     number: "16",
     position: "Захистник",
     nationality: "Грузія",
     photo: "https://shakhtar.com/-/media/fcsd/players/azarov-irakli/azarov_bio_25_26.png?h=610&iar=0&w=473",
     goals: "",
     assist: "1",
     matches: "13",
  },
  {
     name: "Вінісіус Тобіас",
     age: "21",
     number: "17",
     position: "Захистник",
     nationality: "Бразілія",
     photo: "https://shakhtar.com/-/media/fcsd/players/vinicius-tobias/tobias_bio_25_26.png?h=610&iar=0&w=473",
     goals: "2",
     assist: "3",
     matches: "26",
  },
  {
     name: "Алаа Грам",
     age: "24",
     number: "18",
     position: "Захистник",
     nationality: "Туніс",
     photo: "https://shakhtar.com/-/media/fcsd/players/ghram-alaa/ghram_bio_25_26.png?h=610&iar=0&w=473",
     goals: "",
     assist: "",
     matches: "8",
  },
  {
     name: "Микола Матвієнко",
     age: "29",
     number: "22",
     position: "Захистник",
     nationality: "Україна",
     photo: "https://shakhtar.com/-/media/fcsd/players/22-mykola-matviienko/matviienko_bio_25_26.png?h=610&iar=0&w=473",
     goals: "",
     assist: "",
     matches: "28",
  },{
     name: "Юхим Конопля",
     age: "26",
     number: "26",
     position: "Захистник",
     nationality: "Україна",
     photo: "https://shakhtar.com/-/media/fcsd/players/konoplya/konoplia_bio_25_26.png?h=610&iar=0&w=473",
     goals: "2",
     assist: "4",
     matches: "19",
  },
  {
     name: "Мар'ян Фарина",
     age: "22",
     number: "74",
     position: "Захистник",
     nationality: "Україна",
     photo: "https://shakhtar.com/-/media/fcsd/players/faryna-marian/faryna_bio_25_26.png?h=610&iar=0&w=473",
     goals: "",
     assist: "",
     matches: "2",
  },
  {
     name: "Марлон Гомес",
     age: "22",
     number: "6",
     position: "Півзахисник",
     nationality: "Бразілія",
     photo: "https://shakhtar.com/-/media/fcsd/players/gomes-marlon/marlon_gomes_bio_25_26.png?h=610&iar=0&w=473",
     goals: "1",
     assist: "4",
     matches: "26",
  },
  {
     name: "Егіналду",
     age: "21",
     number: "7",
     position: "Півзахисник",
     nationality: "Бразілія",
     photo: "https://shakhtar.com/-/media/fcsd/players/eguinaldo/eguinaldo_bio_25_26.png?h=610&iar=0&w=473",
     goals: "5",
     assist: "2",
     matches: "16",
  },
  {
     name: "Дмитро Криськів",
     age: "25",
     number: "8",
     position: "Піівзахисник",
     nationality: "Україна",
     photo: "https://shakhtar.com/-/media/fcsd/players/kryskiv-dmytro/kryskiv_bio_25_26.png?h=610&iar=0&w=473",
     goals: "",
     assist: "",
     matches: "10",
  },

  {
     name: "Мар'ян Швед",
     age: "28",
     number: "9",
     position: "Півзахисник",
     nationality: "Україна",
     photo: "https://shakhtar.com/-/media/fcsd/players/shved-marian/shved_bio_25_26.png?h=610&iar=0&w=473",
     goals: "",
     assist: "",
     matches: "8",
  },
  {
     name: "Педріньйо",
     age: "27",
     number: "10",
     position: "Півзахисник",
     nationality: "Бразілія",
     photo: "https://shakhtar.com/-/media/fcsd/players/pedrinho/pedrinho_bio_25_26.png?h=610&iar=0&w=473",
     goals: "6",
     assist: "9",
     matches: "25",
  },
  {
     name: "Невертон",
     age: "20",
     number: "11",
     position: "Півзахисник",
     nationality: "Бразілія",
     photo: "https://shakhtar.com/-/media/fcsd/players/newerton/newertton_bio_25_26.png?h=610&iar=0&w=473",
     goals: "5",
     assist: "1",
     matches: "25",
  },
  {
     name: "Ізакі Сілва",
     age: "18",
     number: "14",
     position: "Півзахисник",
     nationality: "Бразілія",
     photo: "https://shakhtar.com/-/media/fcsd/players/isaque-silva/isaque_silva_bio_2025-09-18.png?h=610&iar=0&w=473",
     goals: "4",
     assist: "4",
     matches: "19",
  },
  {
     name: "Антон Глущенко",
     age: "21",
     number: "20",
     position: "Півзахисник",
     nationality: "Україна",
     photo: "https://shakhtar.com/-/media/fcsd/players/hlushchenko/hlushchenko_bio__25_26.png?h=610&iar=0&w=473",
     goals: "1",
     assist: "",
     matches: "5",
  },
  {
     name: "Артем Бондаренко",
     age: "25",
     number: "21",
     position: "Півзахисник",
     nationality: "Україна",
     photo: "https://shakhtar.com/-/media/fcsd/players/bondarenko-artem/bondarenko_bio_25_26.png?h=610&iar=0&w=473",
     goals: "3",
     assist: "4",
     matches: "27",
  },
  {
     name: "Віктор Цуканов",
     age: "19",
     number: "24",
     position: "Півзахисник",
     nationality: "Україна",
     photo: "https://shakhtar.com/-/media/fcsd/players/under_19/tsukanov/tsukanov_bio_25_26.png?h=610&iar=0&w=473",
     goals: "",
     assist: "",
     matches: "1",
  },
  {
     name: "Олег Очеретько",
     age: "22",
     number: "27",
     position: "Півзахисник",
     nationality: "Україна",
     photo: "https://shakhtar.com/-/media/fcsd/players/ocheretko-oleh/ocheretko_bio_25_26.png?h=610&iar=0&w=473",
     goals: "3",
     assist: "2",
     matches: "28",
  },
  {
     name: "Єгор Назарина",
     age: "28",
     number: "29",
     position: "Півзахисник",
     nationality: "Україна",
     photo: "https://shakhtar.com/-/media/fcsd/players/nazaryna/nazaryna_bio_25_26.png?h=610&iar=0&w=473",
     goals: "3",
     assist: "1",
     matches: "17",
  },
  {
     name: "Аліссон Сантана",
     age: "20",
     number: "30",
     position: "Півзахисник",
     nationality: "Бразілія",
     photo: "https://shakhtar.com/-/media/fcsd/players/alisson/alisson_bio_25_26.png?h=610&iar=0&w=473",
     goals: "4",
     assist: "6",
     matches: "13",
  },

  {
     name: "Лукас Феррейра",
     age: "19",
     number: "37",
     position: "Півзахисник",
     nationality: "Бразілія",
     photo: "https://shakhtar.com/-/media/fcsd/players/ferreira-lucas/lukasferreira_bio_25_26.png?h=610&iar=0&w=473",
     goals: "1",
     assist: "1",
     matches: "19",
  },
  {
     name: "Лассіна Траоре",
     age: "24",
     number: "2",
     position: "Нападник",
     nationality: "Буркін-Фасо",
     photo: "https://shakhtar.com/-/media/fcsd/players/traore-lassina/traore_bio_25_26.png?h=610&iar=0&w=473",
     goals: "",
     assist: "",
     matches: "3",
  },
  {
     name: "Кауан Еліас",
     age: "19",
     number: "19",
     position: "Нападник",
     nationality: "Бразілія",
     photo: "https://shakhtar.com/-/media/fcsd/players/elias-kaua/elias_bio_25_26.png?h=610&iar=0&w=473",
     goals: "11",
     assist: "4",
     matches: "26",
  },

  {
     name: "Лука Мейрелліш",
     age: "18",
     number: "49",
     position: "Нападник",
     nationality: "Бразілія",
     photo: "https://shakhtar.com/-/media/fcsd/players/luca-meirelles/luca_meirelles_bio_2025-09-18.png?h=610&iar=0&w=473",
     goals: "8",
     assist: "1",
     matches: "18",
  },
];
window.coaches = [
    {
    name: "Арда Туран",
    age: 38,
    position: "Тренерскій штаб",
    coach: "Головний тренер",
    nationality: "Турція",
    photo: "https://shakhtar.com/-/media/fcsd/coaches/first_team/arda-turan/turan_p2.png?h=610&iar=0&w=473"
  },
  {
    name: "Керем Яваш",
    age: "41",
    position: "Тренерскій штаб",
    coach: "Асистент тренера",
    nationality: "Турція",
    photo: "https://shakhtar.com/-/media/fcsd/coaches/first_team/kerem-yavas/yava_p2.png?h=610&iar=0&w=473",
  },
  {
    name: "Сінан Сарікурт",
    age: "38",
    position: "Тренерскій Штаб",
    coach: "Асистент Тренера",
    nationality: "Турція",
    photo: "https://shakhtar.com/-/media/fcsd/coaches/first_team/sinan-sarikurt/sarkurt_p2.png?h=610&iar=0&w=473",
  },
  {
    name: "Карло Ніколіні",
    age: "55",
    position: "Тренерскій Штаб",
    coach: "Асистент тренера",
    nationality: "Італія",
    photo: "https://shakhtar.com/-/media/fcsd/coaches/first_team/carlo-nicolini/nicolini_p2.png?h=610&iar=0&w=473",
  },
  {
    name: "Окан Джан Янтир",
    age: "46",
    position: "Тренерскій штаб",
    coach: "Особистий консультант",
    nationality: "Турція",
    photo: "https://shakhtar.com/-/media/fcsd/coaches/first_team/okan-can-yantir/yantir_p2.png?h=610&iar=0&w=473",
  },
  {
    name: "Емрех Карокван",
    age: "41",
    position: "Тренерскій штаб",
    coach: "Тренер воротарів",
    nationality: "Турція",
    photo: "https://shakhtar.com/-/media/fcsd/coaches/first_team/emrah-karakovan/karakovan_p2.png?h=610&iar=0&w=473",
  },
  {
    name: "Андрій Пятов",
    age: "41",
    position: "Тренерскій штаб",
    coach: "Тренер воротарів",
    nationality: "Україна",
    photo: "https://shakhtar.com/-/media/fcsd/coaches/first_team/andrii-piatov/piatov_p2_.png?h=610&iar=0&w=473",
  },
  {
    name: "Утку Алемдароглу",
    age: "45",
    position: "Тренерскій штаб",
    coach: "Тренеп із фізподготовки",
    nationality: "Турція",
    photo: "https://shakhtar.com/-/media/fcsd/coaches/first_team/utku-alemdaroglu/alemdarolu_p2.png?h=610&iar=0&w=473",
  },
  {
    name: "Іван Баштовий",
    age: "38",
    position: "Тренерскій штаб",
    coach: "трене із фізподготовки",
    nationality: "Україна",
    photo: "https://shakhtar.com/-/media/fcsd/coaches/first_team/ivan-bashtovyi/bashtovyi_bio_2025.png?h=610&iar=0&w=473",
  },
  {
    name: "радіон Пальцун",
    age: "38",
    position: "Тренерскій штаб",
    coach: "Аналітік",
    nationality: "Україна",
    photo: "https://shakhtar.com/-/media/fcsd/coaches/first_team/radion-paltsun/paltsun_bio_2025.png?h=610&iar=0&w=473",
  },
  {
    name: "Мерт Сомай",
    age: "40",
    position: "Тренерскй штаб",
    coach: "Аналітік",
    nationality: "Турція",
    photo: "https://shakhtar.com/-/media/fcsd/coaches/first_team/mert-somay/somay_p2.png?h=610&iar=0&w=473",
  },
  {
    name: "Олексій Гай",
    age: "43",
    position: "Тренерскій штаб",
    coach: "Аналітік",
    nationality: "Україна",
    photo: "https://shakhtar.com/-/media/fcsd/coaches/first_team/oleksii-hai/gai_p2.png?h=610&iar=0&w=473",
  },
];

window.legends =[
   {
      name: "Андрій Пятов",
      photo: "https://shakhtar.com/-/media/fcsd/players/30-andriy-pyatov/bio_pyatov_2017.png?h=610&iar=0&w=473",
      age: "41",
      nationality: "Україна",
      position: "Воротар",
      matches: "482",
      goals: "0",
      assist: "0",
   },
   {
      name: "Дарійо Срна",
      photo: "https://shakhtar.com/-/media/fcsd/players/33-darijo-srna/srna2_.jpg?h=610&iar=0&w=473",
      age: "43",
      nationality: "Хорватіяя",
      position: "Захисник",
      matches: "536",
      goals: "49",
      assist: "129",
   },
   {
      name: "Жадсон",
      photo: "https://shakhtar.com/-/media/fcsd/legends/j/jadson_halfturn.jpg?h=610&iar=0&w=473",
      age: "42",
      nationality: "Бразілія",
      position: "Півзахисник",
      matches: "272",
      goals: "64",
      assist: "64",
   },
   {
      name: "Андрій Воробей",
      photo: "https://shakhtar.com/-/media/fcsd/legends/vorobey/vorobey-bio.png?h=610&iar=0&w=473",
      age: "47",
      nationality: "Україна",
      position: "Нападник",
      matches: "319",
      goals: "114",
      assist: "49",
   },
   {
      name: "Луїз Адріано",
      photo: "https://shakhtar.com/-/media/fcsd/legends/adriano/adriano-bio.png?h=610&iar=0&w=473",
      age: "38",
      nationality: "Бразілія",
      position: "Нападник",
      matches: "266",
      goals: "128",
      assist: "43",
   },
   {
      name: "Мірча Луческу",
      photo: "https://shakhtar.com/-/media/fcsd/legends/ml/ml.png?h=610&iar=0&w=473",
      age: "80",
      nationality: "Румунія",
      position: "Головний тренер",
      matches: "573",
      goals: "0",
      assist: "0",
   },
];

  window.matches = [
{
 date: "18-12-25",
 opponent: "ФК Ріека",
 time: "22:00",
 score: "0-0",
 place: "Стадіон Генрика Реймана",
 competition: "Ліга Конференцій",
},
{
date: "21-2-26",
opponent: "Карпати Львів",
time: "",
score: "",
place: "Арена Львів",
competition: "УПЛ",
},
{
date: "28-2-26",
opponent: "Верес Рівне",
time: "",
score: "",
place: "Арена Львів",
competition: "УПЛ",
},
{
date: "7-3-26",
opponent: "Олександрія",
time: "",
score: "",
place: "ЦСК Ніка Стадіон",
competition: "УПЛ",
},
{
  date: "14-3-26",
  opponent: "Металіст 1925",
  time: "",
  score: "",
  place: "Арена Львів",
  competition: "УПЛ",
},
{
  date: "21-3-26",
  opponent: "Зоря Луганьск",
  time: "",
  score: "",
  place: "Стадіон імені Валерія Лобановського",
  competition: "УПЛ",
}
];
const kits = {
  home: {
    img: 'https://shop.shakhtar.com/images/thumbnails/900/900/detailed/19/fc-shakhtar-puma-fcsd-home-authentic-jersey-77970601_oexn-le.webp.webp',
    text: 'Класична оранжево-чорна форма. Символ стабільності та характеру клубу.'
  },
  away: {
    img: 'https://shop.shakhtar.com/images/thumbnails/900/900/detailed/19/fc-shakhtar-puma-fcsd-away-authentic-jersey-77970702_l4eh-1a.webp.webp',
    text: 'Світла виїзна форма для складних матчів поза домом.'
  },
  third: {
    img: 'https://shop.shakhtar.com/images/thumbnails/900/900/detailed/19/fc-shakhtar-puma-fcsd-third-authentic-jersey-77970803_0zih-og.webp.webp',
    text: 'Експериментальна форма для єврокубкових вечорів.'
  }
};